// <auto-generated />
namespace Warsztat.DataContexts.IdentityMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class owner : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(owner));
        
        string IMigrationMetadata.Id
        {
            get { return "201901281156459_owner"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
